-- Lucky Élite Select / Supabase
-- 1) En Supabase > SQL Editor pega TODO este archivo y ejecuta.
create extension if not exists pgcrypto;

create table if not exists public.raffles (
  id uuid primary key,
  name text not null,
  tagline text,
  prize text not null,
  price integer not null default 250,
  total_tickets integer not null default 1000,
  draw_at timestamptz not null,
  bonus_threshold integer not null default 300,
  winner_number text
);

create table if not exists public.buyers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  whatsapp text not null,
  city text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  raffle_id uuid not null references public.raffles(id) on delete cascade,
  number text not null,
  status text not null default 'available' check(status in ('available','reserved','paid','winner')),
  buyer_id uuid references public.buyers(id),
  reserved_until timestamptz,
  updated_at timestamptz not null default now(),
  unique(raffle_id,number)
);

insert into public.raffles(id,name,tagline,prize,price,total_tickets,draw_at,bonus_threshold)
values('00000000-0000-0000-0000-000000000001','Lucky Élite Select','La suerte de tu lado','MacBook Air 13” Chip M5 · 16 GB · 512 GB · Azul Medianoche',250,1000,'2026-09-20 20:00:00-06',300)
on conflict(id) do update set name=excluded.name,tagline=excluded.tagline,prize=excluded.prize,price=excluded.price,total_tickets=excluded.total_tickets,draw_at=excluded.draw_at,bonus_threshold=excluded.bonus_threshold;

insert into public.tickets(raffle_id,number)
select '00000000-0000-0000-0000-000000000001', lpad(g::text,3,'0') from generate_series(0,999) g
on conflict do nothing;

alter table public.raffles enable row level security;
alter table public.buyers enable row level security;
alter table public.tickets enable row level security;

drop policy if exists "public read raffle" on public.raffles;
create policy "public read raffle" on public.raffles for select using (true);

drop policy if exists "public read tickets" on public.tickets;
create policy "public read tickets" on public.tickets for select using (true);

-- Solo la función RPC recibe datos del comprador y hace el bloqueo atómico.
create or replace function public.reserve_tickets(
  p_raffle_id uuid,
  p_numbers text[],
  p_name text,
  p_whatsapp text,
  p_city text
) returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  b_id uuid;
  n text;
  bad_count integer;
begin
  if array_length(p_numbers,1) is null or array_length(p_numbers,1)=0 then
    raise exception 'No seleccionaste boletos.';
  end if;
  if array_length(p_numbers,1)>50 then raise exception 'Máximo 50 boletos por operación.'; end if;

  -- Libera apartados vencidos antes de intentar bloquear.
  update tickets set status='available', buyer_id=null, reserved_until=null
  where raffle_id=p_raffle_id and status='reserved' and reserved_until < now();

  -- Bloqueo de filas para evitar que dos personas aparten el mismo boleto.
  perform 1 from tickets where raffle_id=p_raffle_id and number = any(p_numbers)
    and status in ('paid','winner') for update;
  if found then raise exception 'Uno o más boletos ya no están disponibles.'; end if;

  if exists(select 1 from tickets where raffle_id=p_raffle_id and number=any(p_numbers)
      and status='reserved' and reserved_until>=now()) then
    raise exception 'Uno o más boletos están apartados por otra persona.';
  end if;

  insert into buyers(name,whatsapp,city) values(trim(p_name),trim(p_whatsapp),trim(p_city)) returning id into b_id;

  update tickets set status='reserved',buyer_id=b_id,reserved_until=now()+interval '24 hours',updated_at=now()
  where raffle_id=p_raffle_id and number=any(p_numbers);

  return jsonb_build_object('buyer_id',b_id,'numbers',p_numbers,'reserved_until',now()+interval '24 hours');
end $$;

grant execute on function public.reserve_tickets(uuid,text[],text,text,text) to anon,authenticated;

-- IMPORTANTE: para el panel admin, usa Supabase Auth y políticas de escritura.
-- Crea tu usuario administrador en Authentication > Users.
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from auth.users u where u.id=auth.uid() and u.email='CAMBIA_ESTE_CORREO'); $$;

drop policy if exists "admin update tickets" on public.tickets;
create policy "admin update tickets" on public.tickets for update using(public.is_admin()) with check(public.is_admin());

drop policy if exists "admin read buyers" on public.buyers;
create policy "admin read buyers" on public.buyers for select using(public.is_admin());

drop policy if exists "admin update raffle" on public.raffles;
create policy "admin update raffle" on public.raffles for update using(public.is_admin()) with check(public.is_admin());

-- Después de crear tu usuario, reemplaza CAMBIA_ESTE_CORREO por su correo y vuelve a ejecutar SOLO is_admin() y las policies si hace falta.
